version: "3"
services:
  app:
    build: .
    environment:
      - MYSQL_HOST=mysqldb
    ports:
      - "8080:8080"
    networks:
        - oauth2
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=112233
      - MYSQL_DATABASE=oauth
    ports:
        - "3306:3306"
    volumes:
        - mysql:/var/lib/mysql
    networks:
      - oauth2
volumes:
    mysql:
networks:
    oauth2: