version: "3"
services:
  app:
    container_name: spring-oauth2
    build: .
    environment:
      - MYSQL_HOST=mysqldb
    ports:
      - "8080:8080"
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=112233
      - MYSQL_DATABASE=oauth
    ports:
        - "3306:3306"
    volumes:
        - mysql:/var/lib/mysql
volumes:
    mysql: