spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: 112233
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 643221851565-uf68kvbcut70858rpri6cp248t0i7ti8.apps.googleusercontent.com
            client-secret: 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
application:
  oauth2:
    tokenExpiration: 864000000
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    authorizedRedirectUris: http://localhost:3000/oauth2/redirect, http://localhost:9999/oauth2/redirect