spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 643221851565-pnmi3kuuserbnfa652clkba8l6jbqdo7.apps.googleusercontent.com
            client-secret: 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