spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
    username: root
    password: 112233
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 643221851565-326g2gk94b2buq2doluuajvft7is720c.apps.googleusercontent.com
            clientSecret: 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
            redirect-uri: "http://localhost:8080/oauth2/callback/google"
            scope:
              - email
              - profile
  minio:
    endpoint: http://localhost:9000
    bucketName: avatar
    accessKey: tinhtute
    secretKey: vodichtoanvutru
application:
  oauth2:
    accessTokenExpiration: 86400000 # 1 minute
    refreshTokenExpiration: 604800000 # 7 days
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    authorizedRedirectUris: http://localhost:3000/oauth2/redirect, http://localhost:9999/oauth2/redirect